"""user theme and appearance

Revision ID: 0e215572b017
Revises: c0dc7e3971bd
Create Date: 2026-07-30 04:44:25.522010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e215572b017'
down_revision: Union[str, Sequence[str], None] = 'c0dc7e3971bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.Enum('ember', 'tide', 'meridian', 'graphite', 'daylight', 'signal', name='theme', native_enum=False, create_constraint=True), server_default='ember', nullable=False))
    op.add_column('users', sa.Column('appearance', sa.Enum('system', 'light', 'dark', name='appearance', native_enum=False, create_constraint=True), server_default='system', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'appearance')
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
