"""calendar connections

Token columns are LargeBinary here rather than app.crypto.EncryptedString:
migrations describe physical storage and should not import application code,
which is free to move. EncryptedString stores Fernet ciphertext as bytes.

Revision ID: 37ff2959993e
Revises: dd841f2cf071
Create Date: 2026-07-30 02:01:52.580674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ff2959993e'
down_revision: Union[str, Sequence[str], None] = 'dd841f2cf071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token', sa.LargeBinary(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_account_id')
    )
    op.create_index(op.f('ix_calendar_connections_user_id'), 'calendar_connections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_connections_user_id'), table_name='calendar_connections')
    op.drop_table('calendar_connections')
    # ### end Alembic commands ###
