"""scheduling model: events, periods, preferences

Revision ID: c0dc7e3971bd
Revises: 37ff2959993e
Create Date: 2026-07-30 03:42:23.686791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0dc7e3971bd'
down_revision: Union[str, Sequence[str], None] = '37ff2959993e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_periods_end_after_start'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periods_user_id'), 'periods', ['user_id'], unique=False)
    op.create_index('ix_periods_user_starts_at', 'periods', ['user_id', 'starts_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('deadline', 'one_time', name='event_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source', sa.Enum('imported', 'manual', name='event_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expected_prep_minutes', sa.Integer(), nullable=True),
    sa.Column('calendar_connection_id', sa.Integer(), nullable=True),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(event_type = 'one_time'  AND starts_at IS NOT NULL AND ends_at IS NOT NULL AND due_at IS NULL) OR (event_type = 'deadline'  AND due_at IS NOT NULL AND starts_at IS NULL AND ends_at IS NULL)", name='ck_events_times_match_type'),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name='ck_events_end_after_start'),
    sa.CheckConstraint('expected_prep_minutes IS NULL OR expected_prep_minutes > 0', name='ck_events_prep_positive'),
    sa.ForeignKeyConstraint(['calendar_connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_connection_id', 'provider_event_id', name='uq_events_provider_event')
    )
    op.create_index(op.f('ix_events_calendar_connection_id'), 'events', ['calendar_connection_id'], unique=False)
    op.create_index('ix_events_user_due_at', 'events', ['user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_index('ix_events_user_starts_at', 'events', ['user_id', 'starts_at'], unique=False)
    op.create_table('period_events',
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('period_id', 'event_id')
    )
    op.add_column('users', sa.Column('workdays', sa.JSON(), server_default=sa.text("'[0, 1, 2, 3, 4]'"), nullable=False))
    op.add_column('users', sa.Column('day_start', sa.Time(), server_default=sa.text("'09:00'"), nullable=False))
    op.add_column('users', sa.Column('day_end', sa.Time(), server_default=sa.text("'17:00'"), nullable=False))
    op.add_column('users', sa.Column('period_minutes', sa.Integer(), server_default=sa.text('50'), nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    op.drop_column('users', 'workday_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: autogenerate emitted a NOT NULL column with
    # no default, which fails whenever the users table already has rows.
    op.add_column('users', sa.Column(
        'workday_preferences', postgresql.JSON(astext_type=sa.Text()),
        autoincrement=False, nullable=False,
        server_default=sa.text(
            '\'{"monday": "9:00-17:00", "tuesday": "9:00-17:00",'
            ' "wednesday": "9:00-17:00", "thursday": "9:00-17:00",'
            ' "friday": "9:00-17:00"}\'')))
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'period_minutes')
    op.drop_column('users', 'day_end')
    op.drop_column('users', 'day_start')
    op.drop_column('users', 'workdays')
    op.drop_table('period_events')
    op.drop_index('ix_events_user_starts_at', table_name='events')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index('ix_events_user_due_at', table_name='events')
    op.drop_index(op.f('ix_events_calendar_connection_id'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_periods_user_starts_at', table_name='periods')
    op.drop_index(op.f('ix_periods_user_id'), table_name='periods')
    op.drop_table('periods')
    # ### end Alembic commands ###
